

import "./globals.scss";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/core/navbar/navbar";
import Footer from "@/components/core/footer/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <>
              <Navbar />
              {children}
              <Toaster />
              <Footer />
            </>
          </ThemeProvider>
      </body>
    </html>
  );
}

export default RootLayout